site_name: Geodatenprozessierung Dokumentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Run: run.md
  - Reproduce: reproduce.md
  - Troubleshooting: troubleshooting.md
  - Arbeitsaufteilung: aufteilung.md

